services:
    knp_rad_resource_resolver.parameter_caster.variable_caster:
        class: Knp\Rad\ResourceResolver\ParameterCaster\VariableCaster
        public: false
        arguments: [@request_stack]
        tags:
            - { name: knp_rad_resource_resolver.parameter_caster }

    knp_rad_resource_resolver.resource_resolver:
        class: Knp\Rad\ResourceResolver\ResourceResolver
        public: false
        arguments: [@service_container]

    knp_rad_resource_resolver.event_listener.resources_listener:
        class: Knp\Rad\ResourceResolver\EventListener\ResourcesListener
        arguments: [@knp_rad_resource_resolver.resource_resolver]
        tags: 
            - { name: kernel.event_listener, event: kernel.controller, method: resolveResources }
